// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Kawin Viriyaprasopsook",
            "email": "kawin.vir@zercle.tech"
        },
        "license": {
            "name": "MIT License",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/qr/billpayment": {
            "get": {
                "parameters": [
                    {
                        "type": "number",
                        "name": "amount",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "invoice",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "merchan_name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "qr_type",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "ref1",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "ref2",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "ref3",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "suffix",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "tax_id",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/helpers.ResponseForm"
                        }
                    }
                }
            },
            "post": {
                "parameters": [
                    {
                        "description": "transaction detail",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.QrRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/helpers.ResponseForm"
                        }
                    }
                }
            }
        },
        "/api/v1/qr/mypromptqr": {
            "get": {
                "parameters": [
                    {
                        "type": "number",
                        "name": "amount",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "invoice",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "merchan_name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "qr_type",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "ref1",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "ref2",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "ref3",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "suffix",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "tax_id",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/helpers.ResponseForm"
                        }
                    }
                }
            },
            "post": {
                "parameters": [
                    {
                        "description": "transaction detail",
                        "name": "post_request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.QrRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/helpers.ResponseForm"
                        }
                    }
                }
            }
        },
        "/api/v1/qr/qr30": {
            "get": {
                "parameters": [
                    {
                        "type": "number",
                        "name": "amount",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "invoice",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "merchan_name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "qr_type",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "ref1",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "ref2",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "ref3",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "suffix",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "tax_id",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/helpers.ResponseForm"
                        }
                    }
                }
            },
            "post": {
                "parameters": [
                    {
                        "description": "transaction detail",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.QrRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/helpers.ResponseForm"
                        }
                    }
                }
            }
        },
        "/api/v1/qr/qrcs": {
            "get": {
                "parameters": [
                    {
                        "type": "number",
                        "name": "amount",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "invoice",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "merchan_name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "qr_type",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "ref1",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "ref2",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "ref3",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "suffix",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "tax_id",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/helpers.ResponseForm"
                        }
                    }
                }
            },
            "post": {
                "parameters": [
                    {
                        "description": "transaction detail",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.QrRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/helpers.ResponseForm"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "helpers.ResponseError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "source": {},
                "title": {
                    "type": "string"
                }
            }
        },
        "helpers.ResponseForm": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/helpers.ResponseError"
                    }
                },
                "messages": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "result": {},
                "result_info": {
                    "$ref": "#/definitions/helpers.ResultInfo"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "helpers.ResultInfo": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "per_page": {
                    "type": "integer"
                },
                "total_count": {
                    "type": "integer"
                }
            }
        },
        "models.QrRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "invoice": {
                    "type": "string"
                },
                "merchan_name": {
                    "type": "string"
                },
                "qr_type": {
                    "type": "string"
                },
                "ref1": {
                    "type": "string"
                },
                "ref2": {
                    "type": "string"
                },
                "ref3": {
                    "type": "string"
                },
                "suffix": {
                    "type": "string"
                },
                "tax_id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Promptpay QR Services",
	Description:      "This is a sample promtpay QR generator in GO",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
