basePath: /
definitions:
  helpers.ResponseError:
    properties:
      code:
        type: integer
      message:
        type: string
      source: {}
      title:
        type: string
    type: object
  helpers.ResponseForm:
    properties:
      errors:
        items:
          $ref: '#/definitions/helpers.ResponseError'
        type: array
      messages:
        items:
          type: string
        type: array
      result: {}
      result_info:
        $ref: '#/definitions/helpers.ResultInfo'
      success:
        type: boolean
    type: object
  helpers.ResultInfo:
    properties:
      count:
        type: integer
      page:
        type: integer
      per_page:
        type: integer
      total_count:
        type: integer
    type: object
  models.QrRequest:
    properties:
      amount:
        maximum: 9.999999999999e+10
        minimum: 0
        type: number
      invoice:
        maxLength: 20
        type: string
      merchan_name:
        maxLength: 20
        type: string
      qr_type:
        enum:
        - static
        - dynamic
        type: string
      ref1:
        maxLength: 20
        type: string
      ref2:
        maxLength: 20
        type: string
      ref3:
        maxLength: 20
        type: string
      suffix:
        maxLength: 2
        type: string
      tax_id:
        maxLength: 13
        minLength: 10
        type: string
    required:
    - amount
    - ref1
    - tax_id
    type: object
  models.QrResponse:
    properties:
      amount:
        type: number
      data:
        type: string
      image:
        type: string
      invoice:
        type: string
      merchan_name:
        type: string
      qr_type:
        enum:
        - static
        - dynamic
        type: string
      ref1:
        type: string
      ref2:
        type: string
      ref3:
        type: string
      suffix:
        type: string
      tax_id:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: kawin.vir@zercle.tech
    name: Kawin Viriyaprasopsook
    url: https://github.com/zercle/promtpay-qr-services
  description: This is a sample promtpay QR generator in GO
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  title: Promptpay QR Services
  version: "0.1"
paths:
  /api/v1/qr/billpayment:
    get:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - in: query
        maximum: 9.999999999999e+10
        minimum: 0
        name: amount
        required: true
        type: number
      - in: query
        maxLength: 20
        name: invoice
        type: string
      - in: query
        maxLength: 20
        name: merchan_name
        type: string
      - enum:
        - static
        - dynamic
        in: query
        name: qr_type
        type: string
      - in: query
        maxLength: 20
        name: ref1
        required: true
        type: string
      - in: query
        maxLength: 20
        name: ref2
        type: string
      - in: query
        maxLength: 20
        name: ref3
        type: string
      - in: query
        maxLength: 2
        name: suffix
        type: string
      - in: query
        maxLength: 13
        minLength: 10
        name: tax_id
        required: true
        type: string
      - description: response by QR image
        in: query
        name: image
        type: boolean
      produces:
      - application/json
      - image/png
      responses:
        "200":
          description: OK
          schema:
            type: file
    post:
      consumes:
      - application/json
      parameters:
      - description: transaction detail
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.QrRequest'
      - description: response by QR image
        in: query
        name: image
        type: boolean
      produces:
      - application/json
      - image/png
      responses:
        "200":
          description: OK
          schema:
            type: file
  /api/v1/qr/mypromptqr:
    get:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - in: query
        maximum: 9.999999999999e+10
        minimum: 0
        name: amount
        required: true
        type: number
      - in: query
        maxLength: 20
        name: invoice
        type: string
      - in: query
        maxLength: 20
        name: merchan_name
        type: string
      - enum:
        - static
        - dynamic
        in: query
        name: qr_type
        type: string
      - in: query
        maxLength: 20
        name: ref1
        required: true
        type: string
      - in: query
        maxLength: 20
        name: ref2
        type: string
      - in: query
        maxLength: 20
        name: ref3
        type: string
      - in: query
        maxLength: 2
        name: suffix
        type: string
      - in: query
        maxLength: 13
        minLength: 10
        name: tax_id
        required: true
        type: string
      - description: response by QR image
        in: query
        name: image
        type: boolean
      responses:
        "200":
          description: OK
          schema:
            type: file
    post:
      consumes:
      - application/json
      parameters:
      - description: transaction detail
        in: body
        name: post_request
        required: true
        schema:
          $ref: '#/definitions/models.QrRequest'
      - description: response by QR image
        in: query
        name: image
        type: boolean
      responses:
        "200":
          description: OK
          schema:
            type: file
  /api/v1/qr/qr30:
    get:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - in: query
        maximum: 9.999999999999e+10
        minimum: 0
        name: amount
        required: true
        type: number
      - in: query
        maxLength: 20
        name: invoice
        type: string
      - in: query
        maxLength: 20
        name: merchan_name
        type: string
      - enum:
        - static
        - dynamic
        in: query
        name: qr_type
        type: string
      - in: query
        maxLength: 20
        name: ref1
        required: true
        type: string
      - in: query
        maxLength: 20
        name: ref2
        type: string
      - in: query
        maxLength: 20
        name: ref3
        type: string
      - in: query
        maxLength: 2
        name: suffix
        type: string
      - in: query
        maxLength: 13
        minLength: 10
        name: tax_id
        required: true
        type: string
      - description: response by QR image
        in: query
        name: image
        type: boolean
      responses:
        "200":
          description: OK
          schema:
            type: file
    post:
      consumes:
      - application/json
      parameters:
      - description: transaction detail
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.QrRequest'
      - description: response by QR image
        in: query
        name: image
        type: boolean
      responses:
        "200":
          description: OK
          schema:
            type: file
  /api/v1/qr/qrcs:
    get:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - in: query
        maximum: 9.999999999999e+10
        minimum: 0
        name: amount
        required: true
        type: number
      - in: query
        maxLength: 20
        name: invoice
        type: string
      - in: query
        maxLength: 20
        name: merchan_name
        type: string
      - enum:
        - static
        - dynamic
        in: query
        name: qr_type
        type: string
      - in: query
        maxLength: 20
        name: ref1
        required: true
        type: string
      - in: query
        maxLength: 20
        name: ref2
        type: string
      - in: query
        maxLength: 20
        name: ref3
        type: string
      - in: query
        maxLength: 2
        name: suffix
        type: string
      - in: query
        maxLength: 13
        minLength: 10
        name: tax_id
        required: true
        type: string
      - description: response by QR image
        in: query
        name: image
        type: boolean
      responses:
        "200":
          description: OK
          schema:
            type: file
    post:
      consumes:
      - application/json
      parameters:
      - description: transaction detail
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.QrRequest'
      - description: response by QR image
        in: query
        name: image
        type: boolean
      responses:
        "200":
          description: OK
          schema:
            type: file
swagger: "2.0"
